import 'dart:io';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/report.dart';

class PdfService {
  Future<File> generateReport(Report report) async {
    final pdf = pw.Document();

    final image = pw.MemoryImage(
      File(report.imagePath).readAsBytesSync(),
    );

    final bool cataract =
        report.prediction == "Possible Cataract";

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [

              pw.Center(
                child: pw.Text(
                  "AI Cataract Screening Report",
                  style: pw.TextStyle(
                    fontSize: 24,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),

              pw.SizedBox(height: 20),

              pw.Text(
                "Eye Image",
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),

              pw.SizedBox(height: 10),

              pw.Center(
                child: pw.Container(
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(
                      color: PdfColors.grey,
                    ),
                  ),
                  padding: const pw.EdgeInsets.all(8),
                  child: pw.Image(
                    image,
                    width: 220,
                    height: 220,
                    fit: pw.BoxFit.cover,
                  ),
                ),
              ),

              pw.SizedBox(height: 20),

              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey200,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Column(
                  crossAxisAlignment:
                      pw.CrossAxisAlignment.start,
                  children: [

                    pw.Text(
                      "Report Summary",
                      style: pw.TextStyle(
                        fontSize: 18,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),

                    pw.SizedBox(height: 10),

                    pw.Text(
                      "Diagnosis",
                      style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),

                    pw.Container(
                      margin: const pw.EdgeInsets.only(top: 5,bottom:10),
                      padding: const pw.EdgeInsets.symmetric(
                        horizontal:12,
                        vertical:6,
                      ),
                      color: cataract
                          ? PdfColors.red100
                          : PdfColors.green100,
                      child: pw.Text(report.prediction),
                    ),

                    pw.Text(
                      "Confidence : ${(report.confidence*100).toStringAsFixed(2)}%",
                    ),

                    pw.SizedBox(height:8),

                    pw.Text(
                      "Screening Date : ${DateFormat("dd MMM yyyy • hh:mm a").format(DateTime.parse(report.screeningDate))}",
                    ),
                  ],
                ),
              ),

              pw.SizedBox(height:20),

              pw.Text(
                "Recommendation",
                style: pw.TextStyle(
                  fontSize:18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),

              pw.SizedBox(height:8),

              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  color: PdfColors.amber100,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Text(
                  cataract
                  ? "Possible cataract detected. Please consult an ophthalmologist for a comprehensive eye examination."
                  : "No signs of cataract detected. Routine eye examination is recommended every 6–12 months.",
                ),
              ),

              pw.Spacer(),

              pw.Divider(),

              pw.Center(
                child: pw.Text(
                  "Generated by AI Cataract Screening System",
                  style: const pw.TextStyle(
                    fontSize:12,
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );

    final directory = Directory.systemTemp;

    final file = File(
      "${directory.path}/report_${report.reportId}.pdf",
    );

    await file.writeAsBytes(await pdf.save());

    return file;
  }
}
